### PR TITLE
Issue #909: fixed bug that caused ObjectInformatieObject deletion to …

### PR DESCRIPTION
**Pull request by stevenbal**
…not cascade to zrc

### CODE REVIEW

**Comment by joeribekker** [comment]
add to whitelist

**Comment by joeribekker** [comment]
@stevenbal Please do:

> The code for deletion and creation are now so different, they can basically be in their respective functions.

Make sure to take the change to add auth header into account that was added recently

**Comment by joeribekker** [comment]
Ik laat deze even hangen ivm de refactor dat een relatie aangemaakt/verwijderd wordt in het ZRC/DRC, en dat de sync dus andersom werkt.

**Comment by sergei-maertens** [comment]
Fixed during refactor of relation direction.

**Pull request closed without merging**
